using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler002
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("PROJECT EULER PROBLEM #002: EVEN FIBONACCI NUMBERS");
            Console.WriteLine();
            Console.WriteLine("Each new term in the Fibonacci sequence is generated by \nadding the previous two terms.");
            Console.WriteLine("By starting with 1 and 2, the first 10 terms will be: \n\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\n");
            Console.WriteLine("By considering the terms in the Fibonacci sequence whose \nvalues do not exceed four million (4000000),");
            Console.WriteLine("find the sum of the even-valued terms.");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine("Result: {0}", SumOfAllEvenNumbersFibonacci(4000000));
            Console.ReadLine();
        }

        /**
         * Returns the sum of all even-valued terms in the Fibonacci sequence up to a given limit.
         * 
         * @param   limit      int      the top limit of the Fibonacci sequence.
         * @return  sum        int      the sum of all even-valued numbers.
         **/
        private static int SumOfAllEvenNumbersFibonacci(int limit)
        {
            int a = 1,          // First number in the fibonacci sequence (1)
                b = 1,          // Second number in the fibonacci sequence (1)
                c = a + b,      // Third number in the fibonacci sequence (2)          
                sum = 0;        // Sum of all even numbers in the fibonacci sequence

            while (c < limit)
            {
                // Assuming every third number in the Fibonacci sequence is even,
                // there's no need for testing every iteration.
                sum += c;

                // 1, 1, 2, 3, 4, 8, 13, 21, 34, 55, 89, 144, ...
                // a, b, c, a, b, c,  a,  b,  c,  a,  b,   c
                a = b + c;
                b = c + a;
                c = a + b;
            }

            return sum;
        }
    }
}
